#!/usr/bin/env python3
import argparse
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from sys import exit

# parser 
parser = argparse.ArgumentParser()
parser.add_argument("-u", type=str, help="link to the site")
parser.add_argument("-p", type=str, help="path to the file", required=True)

args = parser.parse_args()

# driver 
driver = webdriver.Firefox()

class User():
    def __init__(self, name, lastname, login, desc):
        self.name = name
        self.lastname = lastname
        self.login = login
        self.desc = desc

    def __str__(self):
        return "name: "+ self.name + ", lastname: " + self.lastname + ", login: " + self.login  + ", desc: " + self.desc

def csv2object(csvname: str) -> [User]:
    if not os.path.isfile(csvname):
        print("file does not exist")
        exit(1)
    f = open(csvname, "r")
    users = []
    for line in f.readlines():
        spline = line.split(";")
        users.append(User(spline[0].split('"')[1], spline[1].split('"')[1], spline[2].split('"')[1], spline[1].split('"')[1]))
    return users

url = "http://localhost:5000"
if args.u:
    url = args.u

users = csv2object(args.p)
for user in users:
    driver.get(url + "/add_user")
    name = driver.find_element(By.ID, "name")
    name.send_keys(user.name)
    ln = driver.find_element(By.ID, "lastname")
    ln.send_keys(user.lastname)
    login = driver.find_element(By.ID, "login")
    login.send_keys(user.login)
    desc = driver.find_element(By.ID, "desc")
    desc.send_keys(user.desc)
    name.submit()

driver.close()

